<?php

namespace App\Actions;

use App\Http\Resources\ProductResource;
use App\Models\Product;
use App\Models\ProductModel;
use Genocide\Radiocrud\Services\ActionService\ActionService;

class ProductAction extends ActionService
{
    public function __construct()
    {
        $this
            ->setModel(ProductModel::class)
            ->setResource(ProductResource::class)
            ->setValidationRules([
                'store' => [
                    'category_id' => ['required', 'integer', 'between:1,' . str_repeat('9', 18)],
                    'title' => ['required', 'string', 'max:150'],
                    'description' => ['string', 'max:2500'],
                    'image' => ['required', 'file', 'mimes:png,jpg,jpeg,svg', 'max:5000']
                ],
                'update' => [
                    'category_id' => ['integer', 'between:1,' . str_repeat('9', 18)],
                    'title' => ['string', 'max:150'],
                    'description' => ['nullable', 'string', 'max:2500'],
                    'image' => ['file', 'mimes:png,jpg,jpeg,svg', 'max:5000'],
                    'date' => ['date_format:Y-m-d']
                ],
                'getQuery' => [
                    'category_id' => ['string', 'max:20']
                ]
            ])
            ->setCasts([
                'image' => ['file']
            ])
            ->setQueryToEloquentClosures([
                'category_id' => function (&$eloquent, $query)
                {
                    $eloquent = $eloquent->where('category_id', $query['category_id']);
                }
            ]);

        parent::__construct();
    }

    public function delete(callable $deleting = null): mixed
    {
        $deleting = function ($eloquent) use ($deleting)
        {
            foreach ($eloquent->get() AS $product)
            {
                if (is_file($product->image))
                {
                    unlink($product->image);
                }
            }

            if (is_callable($deleting))
            {
                $deleting($eloquent);
            }
        };
        return parent::delete($deleting);
    }

    public function update(array $updateData, callable $updating = null): bool|int
    {
        $updating = function ($eloquent, $updateData){
            foreach ($eloquent->get() AS $product)
            {
                if (isset($updateData['image']) && is_file($product->image))
                {
                    unlink($product->image);
                }
            }
        };
        return parent::update($updateData, $updating); // TODO: Change the autogenerated stub
    }
}
